# Recommender Workflow 2 of 2: Deploy model
#
# Part of the project "Gradient End-to-End: A Recommender System using Notebooks and Workflows"
# at https://docs.paperspace.com/gradient/get-started/tutorials-list/end-to-end-example
# See that URL for instructions on how to use
# This file is called from the Gradient Notebook deep_learning_recommender_tf.ipynb
# A deployed model is output, to which inference data can then be sent in the following section of the Notebook [1]
# The project GitHub repository, which includes this file, is at https://github.com/gradient-ai/Deep-Learning-Recommender-TF
#
# [1] NOTE: The Notebook section in which inference data is to be sent is pending support from the product,
# but is shown there for completeness. Also, on the public cluster, job 2 will fail due to the lack of a --clusterID
# argument. But model deploy support will supersede this.
#
# Last updated: Nov 03rd 2021

defaults:
  resources:
    instance-type: C4
  env:
    PAPERSPACE_API_KEY: secret:api_key_recommender

jobs:

  # 1. Upload model
  #
  # This makes the model visible to the deploy step, and gets its ID
  # The